env: "local"
http_server:
  port: "8080"
  timeout: 4s
  idle_timeout: 60s
  swagger_enabled: true
database:
  net: "tcp"
  server: ":3306"
  db_name: "NorthBridgeBackend"
  user: "root"
  password: "root"
  time_zone: "UTC"
  timeout: 2s
  max_idle_connections: 40
  max_open_connections: 40
limiter:
  rps: 10
  burst: 20
  ttl: 10m
auth:
  jwt:
    access_token_ttl: 10m
    refresh_token_ttl: 720h
    signing_key: "notasecret"
  password_salt: "notasecret"
  verification_code_length: 10
smtp:
  host: "smtp.gmail.com"
  port: 583
  from: "somemail@gmail.com"
  pass: "notasecret"
email:
  enabled: false
  templates:
    verification: "./templates/verification_email.html"